### ISSUE TITLE
No licence

### ISSUE THREAD

**Issue by ozbenh** [JackOfMostTrades/aws-kms-pkcs11#10]
Hi !

I am investigating using your library for binary signing. Unfortunately I can't really do so unless you provide some kind of licence by which I can use the code.

**Comment by JackOfMostTrades** [comment]
Oops, thanks for pointing that out. I've added an MIT license to the project.

**Comment by ozbenh** [comment]
Thanks ! I'm working on making it work with pesign (which uses the nss hell hole). Slowly getting there, I'll send a PR when I"m done
