### ISSUE TITLE
Set model/manufactorer for returned tokens

### ISSUE THREAD

**Issue by hongkongkiwi** [JackOfMostTrades/aws-kms-pkcs11#12]
Hi there,

Is it possible to set the model and/or manufactorer for each token to 'aws' or a string defined in config?

I would like to use this pkcs11 url to only show the tokens from this plugin:
`p11tool --list-token pkcs11:model=aws`

**Comment by JackOfMostTrades** [comment]
Yea, I think that's fair. Looking at the docs I think setting a "manufacturerID" probably makes the most sense. Any objection to hardcoding that to "aws_kms"? You should then be able to select for that with `p11tool --list-token pkcs11:library-manufacturer=aws_kms`

**Comment by hongkongkiwi** [comment]
That sounds perfect 👍 very helpful :)--
Sent from Gmail Mobile

**Comment by JackOfMostTrades** [comment]
Done: https://github.com/JackOfMostTrades/aws-kms-pkcs11/commit/205b0ba1f19281bf257b71a5273bab48b13df46b

**Comment by hongkongkiwi** [comment]
Thanks! Works well with: `p11tool --info pkcs11:manufacturer=aws_kms`
