### ISSUE TITLE
signing via openssl fails 

### ISSUE THREAD

**Issue by ozbenh** [JackOfMostTrades/aws-kms-pkcs11#16]
I'm having an odd error:
```
AWS_KMS: Invalid data length for SHA256 RSA signature: 2560
```

Looking at the code, something isn't right (or I'm missing something ?)

```
    Aws::KMS::Model::SignRequest req;
    req.SetKeyId(slot.GetKmsKeyId());
    switch (session->sign_mechanism) {
        case CKM_ECDSA:
            req.SetMessage(Aws::Utils::CryptoBuffer(Aws::Utils::ByteBuffer(pData, ulDataLen)));
            req.SetMessageType(Aws::KMS::Model::MessageType::DIGEST);
            req.SetSigningAlgorithm(Aws::KMS::Model::SigningAlgorithmSpec::ECDSA_SHA_256);
            break;
        case CKM_RSA_PKCS:
            if (ulDataLen <= 32) {
                req.SetMessage(Aws::Utils::CryptoBuffer(Aws::Utils::ByteBuffer(pData, ulDataLen)));
            } else if (has_prefix(pData, ulDataLen, rsa_id_sha256, sizeof(rsa_id_sha256))) {
                // Strip the digest algorithm identifier if it has been provided
                req.SetMessage(Aws::Utils::CryptoBuffer(Aws::Utils::ByteBuffer(pData + sizeof(rsa_id_sha256), ulDataLen - sizeof(rsa_id_sha256))));
            } else {
                debug("Invalid data length for SHA256 RSA signature: %d", ulDataLen);
                return CKR_ARGUMENTS_BAD;
            }
            req.SetMessageType(Aws::KMS::Model::MessageType::DIGEST);
            req.SetSigningAlgorithm(Aws::KMS::Model::SigningAlgorithmSpec::RSASSA_PKCS1_V1_5_SHA_256);
            break;
        default:
            return CKR_ARGUMENTS_BAD;
    }
```

So look at the RSA case. First why that business with trying to strip a prefix ? Under what circumstances would the data buffer to be signed be prefixed ? Where is that documented ? I couldn't find anything ... 

Then you apply a limit of 32-bytes to the message that can be signed (but only in the non-prefix case, yuou don't check for a limit in the prefix case). However, openssl is passing us 2560 bytes.... (and afaik KMS can sign up to 4096 bytes).

What am I missing here ? :-)

**Comment by ozbenh** [comment]
Note: I'm basically following your README.md example using an arbitrary large file (larger than 2560 bytes) as input

**Comment by ozbenh** [comment]
Hrm.. ok so you expect to be getting a digest which indeed shouldn't be that big... I'm not sure what openssl is smoking here .. ugh.

**Comment by JackOfMostTrades** [comment]
So I'm just _finally_ circling around to looking at this, and it does seem like the pkeyutl example in the README doesn't quite play nice with RSA keys (I just end up testing EC keys in my workflow). With RSA keys it seems like you need to supply a hint about what digest you're using because of all the weird digest identifier prefixes that get prepended to digests under the weird `RSASSA_PKCS1_V1_5_*` spec. I think it's just a matter of passing in `-pkeyopt digest:sha256` option when doing both the pkeyutl sign and verify operations.

**Comment by JackOfMostTrades** [comment]
Yea, the pkeyutl does expect `foo` to be the digest (not the raw message). I also just checked and for RSA keys _only_ you have to pass in the `-pkeyutl digest:sha256` option so that openssl expects/uses that digest algorithm identifier prefix. Added a note about that option to the README.

**Comment by ozbenh** [comment]
Thanks  !
