### ISSUE TITLE
Signing Kernel Modules - Certificate not found

### ISSUE THREAD

**Issue by hongkongkiwi** [JackOfMostTrades/aws-kms-pkcs11#5]
Hi Ian,

Thanks for the help with RAUC. I'm on to the next mission which is to sign kernel modules after building.

I've just tested using openssl and everything seems ok, but when I attempt to build the krenel it shows error:
```
  EXTRACT_CERTS   pkcs11:
AWS_KMS: Debug enabled.
AWS_KMS: Attempting to load config from path: /etc/aws-kms-pkcs11/config.json
AWS_KMS: Attempting to load config from path: /root/.config/aws-kms-pkcs11/config.json
AWS_KMS: Skipping config because we couldn't open the file.
AWS_KMS: Configured to use AWS key: 8e6426ad-dbd5-4b86-8446-b8adc503904c
AWS_KMS: Configured to use AWS region: us-west-1
  GZIP    kernel/config_data.gz
  CHK     kernel/config_data.h
  UPD     kernel/config_data.h
  CC      kernel/configs.o
  LD      kernel/built-in.o
AWS_KMS: Successfully fetched public key data.
Certificate not found.
At main.c:135:
- SSL error:FFFFFFFF80066065:pkcs11 engine:ctx_ctrl_load_cert:object not found: eng_back.c:593
extract-cert: Get X.509 from PKCS#11: Success
rm: cannot remove 'certs/signing_key.x509': No such file or directory
make[1]: *** [certs/Makefile:98: certs/signing_key.x509] Error 1
make: *** [Makefile:1029: certs] Error 2
make: Leaving directory '/root/kernel'
```

Any ideas what could cause this? 

To build a kernel module with signing I've got this set in my kernel config:
```
---- snip ----
CONFIG_MODULE_SIG=y
CONFIG_MODULE_SIG_SHA256=y
CONFIG_MODULE_SIG_KEY="pkcs11:"
----- snip ----
```

**Comment by JackOfMostTrades** [comment]
Yea, I noticed the same thing with RAUC; all of the examples were pulling both the cert and key from the pkcs11 provider but that project fortunately allowed you to split the arguments and take the cert from the filesystem and key from the pkcs11 module. But there's no reason we couldn't extend the config to allow you to reference filesystem certs and expose those through the pkcs11 module. I'll take a crack at that shortly.

**Comment by JackOfMostTrades** [comment]
The latest commit includes support for adding a certificate to configured key slots. Check out the README for details. Based on playing with `p11tool` it seems to be working, but I didn't try actually building a kernel to see if it works there. If you get a chance to try it, let me know and I can add the kernel signing example to the README.

**Comment by hongkongkiwi** [comment]
Awesome! I'll test and report back.

Quick question, if both a `certificate` and `certificate_path` are present. Which one takes priority?

Also, are certificate chains supported? Not sure if that's a dumb question or not so ignore if so. I will use one of the slots for a signed intermediate key and I thought maybe it makes sense to pass the whole chain back as a certificate? but I'm not sure if that's supported or useful.

**Comment by JackOfMostTrades** [comment]
I believe `certificate_path` would take precedence, but that's just because of how I ordered the code. You should really just specify one or the other.

I'm reading some PKCS#11 docs and from my understanding chains are supported in the sense that a single slot can just have multiple certificate objects, but it becomes hard to distinguish between the leaf certificate versus any intermediate certificates. If it makes sense to do some it's a pretty simple tweak to support arrays for the `certificate` / `certificate_path` properties, but I think I'd like to an example of a PKCS#11 consumer that can take advantage of that first.

**Comment by hongkongkiwi** [comment]
Got this working successfully signing :) Thanks.
